name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          PATH: ${{ secrets.SERVER_PATH }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script_stop: true
          script: |
            echo "Pulling latest changes from repository..."
            cd "$PATH"
            git pull
            echo "Restarting Docker container..."
            docker compose -f docker-compose.prod.yaml up -d --build
